spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    # because the only endpoints in the app expose fields that are exactly the same as the fields on the ORM entities
    # we use the entities as dto objects for simplicity and conciseness (no useless dto and mappers)
    # open-in-view: false is important because it prevents the view (serialization) accessing the database (should be avoided)
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
